# Q1

In [1]:
import numpy as np
x=int(input("Enter columns: "))
y=int(input("Enter rows: "))
def matrix_input():
    x1=[]
    for i in range(0,y):
        a=[]
        for j in range(0,x):
            a.append(int(input()))
        x1.append(a)
    return x1
l1=matrix_input()
l2=matrix_input()
print (np.array(l1) + np.array(l2))

Enter columns: 2
Enter rows: 2
14
15
16
17
16
15
14
13
[[30 30]
 [30 30]]


# Q2

In [2]:
import numpy as np
def matrix_input():
    x=int(input("Enter columns: "))
    y=int(input("Enter rows: "))
    x1=[]
    for i in range(0,y):
        a=[]
        for j in range(0,x):
            a.append(int(input()))
        x1.append(a)
    return x1
l1=matrix_input()
print(l1)
l2=matrix_input()
print(l2)
print (np.dot(l1,l2))

Enter columns: 2
Enter rows: 2
1
2
3
4
[[1, 2], [3, 4]]
Enter columns: 2
Enter rows: 2
1
2
3
4
[[1, 2], [3, 4]]
[[ 7 10]
 [15 22]]


# Q3

In [3]:
def matrix_input():
    x=int(input("Enter columns: "))
    y=int(input("Enter rows: "))
    x1=[]
    for i in range(0,y):
        a=[]
        for j in range(0,x):
            a.append(int(input()))
        x1.append(a)
    return x1
l1=matrix_input()
print(np.transpose(l1))

Enter columns: 2
Enter rows: 2
1
2
3
4
[[1 3]
 [2 4]]


# Q4

In [4]:
my_str = input("Enter a string: ")
words = [word.lower() for word in my_str.split()]
words.sort()
print("The sorted words are:")
for word in words:
    print(word)

Enter a string: Hi I am Harsh
The sorted words are:
am
harsh
hi
i


# Q5

In [8]:
import string
my_str = input("Enter a string: ")
no_punct = ""
for char in my_str:
    if char not in string.punctuation:
        no_punct = no_punct + char
print(no_punct)

Enter a string: Hi I @am Ha@rs$h
Hi I am Harsh
